# Generated by Django 6.0.4 on 2026-05-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artwork', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField()),
                ('date_of_bid', models.DateTimeField(auto_now_add=True)),
                ('expiration_date', models.DateTimeField()),
                ('status', models.CharField(max_length=50)),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.artwork')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.buyer')),
            ],
        ),
    ]
