# Generated by Django 6.0.4 on 2026-05-13 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalize_bid', '0001_initial'),
        ('user', '0002_alter_user_bio_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('national_id', models.CharField(max_length=100)),
                ('Street_name', models.CharField(max_length=100)),
                ('City', models.CharField(max_length=100)),
                ('Postal_code', models.CharField(max_length=100)),
                ('Country', models.CharField(max_length=100)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalize_bid', to='finalize_bid.bid')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='finalize_bid', to='user.buyer')),
            ],
        ),
    ]
