# Generated by Django 6.0.4 on 2026-05-14 10:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finalize_bid', '0002_contact_information'),
        ('user', '0002_alter_user_bio_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank_transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_account', models.CharField(max_length=100)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer', to='finalize_bid.bid')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bank_transfer', to='user.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Credit_card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cvc', models.IntegerField()),
                ('expiry_date', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
                ('cardholder_name', models.CharField(max_length=100)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='finalize_bid.bid')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_card', to='user.buyer')),
            ],
        ),
        migrations.CreateModel(
            name='Wire_transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.IntegerField()),
                ('routing_number', models.IntegerField()),
                ('bank_name', models.CharField(max_length=100)),
                ('bid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wire_transfer', to='finalize_bid.bid')),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='wire_transfer', to='user.buyer')),
            ],
        ),
    ]
