# Generated by Django 6.0.4 on 2026-05-09 14:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('dimensions', models.CharField(max_length=100)),
                ('edition', models.CharField(blank=True, max_length=100)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='artwork_thumbnails/')),
                ('medium', models.CharField(max_length=100)),
                ('style', models.CharField(max_length=100)),
                ('bid_price', models.IntegerField()),
                ('listing_date', models.DateField()),
                ('year_of_creation', models.IntegerField()),
                ('provenance', models.TextField(blank=True)),
                ('bid_status', models.CharField(max_length=50)),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='user.seller')),
            ],
        ),
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='artwork_gallery/')),
                ('artwork', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='artwork.artwork')),
            ],
        ),
    ]
