# Generated by Django 6.0.4 on 2026-05-12 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
        ('user', '0002_alter_user_bio_alter_user_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('style', models.CharField(max_length=100)),
                ('explanation', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='artist',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='user.artist'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='artwork',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artworks', to='artwork.style'),
        ),
    ]
