# Generated by Django 6.0.4 on 2026-05-13 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_style_artwork_artist_alter_artwork_style'),
    ]

    operations = [
        migrations.AlterField(
            model_name='style',
            name='explanation',
            field=models.CharField(max_length=200),
        ),
    ]
