# Generated by Django 6.0.4 on 2026-05-16 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0003_alter_style_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='start_bid_price',
            field=models.CharField(default='200', max_length=200),
            preserve_default=False,
        ),
    ]
